/* 인터페이스-데이터셋관리 */
DROP TABLE TAN0508 
	CASCADE CONSTRAINTS;

/* 인터페이스-데이터매핑관리 */
DROP TABLE TAN0509 
	CASCADE CONSTRAINTS;

/* 인터페이스-데이터셋관리 */
CREATE TABLE TAN0508 (
	DATASET_ID VARCHAR(50) NOT NULL, /* 데이터셋ID */
	INTERFACE_ID VARCHAR(50) NOT NULL, /* 인터페이스ID */
	SEQ INTEGER NOT NULL, /* 순번 */
	IO_TYPE VARCHAR(255) NOT NULL, /* IO구분 */
	DEL_YN VARCHAR(1) DEFAULT 'N' NOT NULL, /* 삭제구분 */
	REG_DATE VARCHAR(17) NOT NULL, /* 등록일 */
	REG_USER VARCHAR(100) NOT NULL, /* 등록자 */
	MOD_DATE VARCHAR(17), /* 최종수정일 */
	MOD_USER VARCHAR(100) /* 최종수정자 */
);

COMMENT ON TABLE TAN0508 IS '인터페이스-데이터셋관리';

COMMENT ON COLUMN TAN0508.DATASET_ID IS '데이터셋ID';

COMMENT ON COLUMN TAN0508.INTERFACE_ID IS '인터페이스ID';

COMMENT ON COLUMN TAN0508.SEQ IS '순번';

COMMENT ON COLUMN TAN0508.IO_TYPE IS 'IO구분';

COMMENT ON COLUMN TAN0508.DEL_YN IS '삭제구분';

COMMENT ON COLUMN TAN0508.REG_DATE IS '등록일';

COMMENT ON COLUMN TAN0508.REG_USER IS '등록자';

COMMENT ON COLUMN TAN0508.MOD_DATE IS '최종수정일';

COMMENT ON COLUMN TAN0508.MOD_USER IS '최종수정자';

CREATE UNIQUE INDEX PK_TAN0508
	ON TAN0508 (
		DATASET_ID ASC,
		INTERFACE_ID ASC,
		SEQ ASC
	);

/* 인터페이스-데이터매핑관리 */
CREATE TABLE TAN0509 (
	INTERFACE_ID VARCHAR(50) NOT NULL, /* 인터페이스ID */
	MAP_ID VARCHAR(50) NOT NULL, /* 데이터매핑ID */
	SEQ INTEGER NOT NULL, /* 순번 */
	IO_TYPE VARCHAR(255) NOT NULL, /* IO구분 */
	DEL_YN VARCHAR(1) DEFAULT 'N' NOT NULL, /* 삭제구분 */
	REG_DATE VARCHAR(17) NOT NULL, /* 등록일 */
	REG_USER VARCHAR(100) NOT NULL, /* 등록자 */
	MOD_DATE VARCHAR(17), /* 최종수정일 */
	MOD_USER VARCHAR(100) /* 최종수정자 */
);

COMMENT ON TABLE TAN0509 IS '인터페이스-데이터매핑관리';

COMMENT ON COLUMN TAN0509.INTERFACE_ID IS '인터페이스ID';

COMMENT ON COLUMN TAN0509.MAP_ID IS '데이터매핑ID';

COMMENT ON COLUMN TAN0509.SEQ IS '순번';

COMMENT ON COLUMN TAN0509.IO_TYPE IS 'IO구분';

COMMENT ON COLUMN TAN0509.DEL_YN IS '삭제구분';

COMMENT ON COLUMN TAN0509.REG_DATE IS '등록일';

COMMENT ON COLUMN TAN0509.REG_USER IS '등록자';

COMMENT ON COLUMN TAN0509.MOD_DATE IS '최종수정일';

COMMENT ON COLUMN TAN0509.MOD_USER IS '최종수정자';

CREATE UNIQUE INDEX PK_TAN0509
	ON TAN0509 (
		INTERFACE_ID ASC,
		MAP_ID ASC,
		SEQ ASC
	);

		   