SELECT * FROM tsu0302 WHERE ATTRIBUTE_NM LIKE '%model%';

SELECT * FROM tan0506;
SELECT * FROM tan0507;

SELECT * FROM trt0901 WHERE INTERFACE_MID  = '143' AND  DEPLOY_DATE  = '20201224164654';

SELECT max(VERSION) AS VERSION FROM trt0102 WHERE INTERFACE_MID = '142';

SELECT * FROM tan0201 WHERE INTEGRATION_ID  LIKE '%4';

SELECT * FROM trt0101 WHERE INTERFACE_ID  = 'F@00000426';

SELECT * FROM tsu0301 WHERE level1 = 'AN' AND LEVEL2  = '12';


SELECT * FROM trt0202;

SELECT * FROM tsu0302 WHERE ATTRIBUTE_NM LIKE '%system.endpoint.implementation%';


SELECT * FROM tan0213;

SELECT * FROM tsu0301 WHERE LEVEL1 = 'AN' AND LEVEL2 = '08';
--22f99efb-97a7-489f-9d9e-e40fcc9698a1
COMMIT;
/* 버전 */
//버전당 32K

UPDATE TVS0101
		SET HEAD        	 = (
			CASE VERSION 
				WHEN 'c3c6f023-9ab0-4050-929d-ede271e431cf' THEN 'Y'
			ELSE 'N'
			END 
		)
		WHERE DATA_TYPE 	 = '100'
		  AND DATA_ID 		 = '156'
		  ;
		 
SELECT * FROM tan0101 WHERE REQUIREMENT_ID  = 'RQ00000428';

SELECT * FROM tsu0302 WHERE "PACKAGE" = 'version';



INSERT INTO IIPSHL.TSU0302
("PACKAGE", ATTRIBUTE_ID, IDX, ATTRIBUTE_NM, ATTRIBUTE_VALUE, COMMENTS, DEL_YN, REG_DATE, REG_USER, MOD_DATE, MOD_USER)
VALUES('version', 'control.on.dataset', 1, 'version.control.on.dataset', 'true', 'DataSet버전관리여부', 'N', to_char(sysdate,'yyyymmddHH24miss'), 'iip', NULL, NULL);

INSERT INTO IIPSHL.TSU0302
("PACKAGE", ATTRIBUTE_ID, IDX, ATTRIBUTE_NM, ATTRIBUTE_VALUE, COMMENTS, DEL_YN, REG_DATE, REG_USER, MOD_DATE, MOD_USER)
VALUES('version', 'control.on.datamap', 1, 'version.control.on.datamap', 'true', 'DataMap버전관리여부', 'N', to_char(sysdate,'yyyymmddHH24miss'), 'iip', NULL, NULL);


COMMIT;
SELECT * FROM trt0501;





SELECT * FROM TAN0502;

ALTER TABLE TAN0502 add(USER_KEY_YN VARCHAR(1) DEFAULT 'N');
COMMENT ON COLUMN TAN0502.USER_KEY_YN IS '이용자식별값속성';

SELECT * FROM TVS0101  ORDER BY COMMIT_DATE DESC ;

SELECT sum(CONTENTS_SIZE) FROM TVS0101  ORDER BY COMMIT_DATE DESC ;

SELECT * FROM TVS0101 WHERE DATA_ID = 'RQ00000430' ORDER BY VERSION_NUMBER DESC ;

DELETE FROM TVS0101;
COMMIT;
SELECT * FROM tan0101 WHERE DEL_YN = 'N';

SELECT REQUIREMENT_ID FROM tan0101 WHERE INTERFACE_ID  = 'F@00000430' AND DEL_YN = 'N' ;
SELECT REQUIREMENT_ID FROM TAN0101 WHERE INTERFACE_ID = 'F@00000430' AND DEL_YN = 'N' ORDER BY REG_DATE ;
SELECT *FROM tan0221;

SELECT  * FROM tsu0301 WHERE LEVEL1  ='AN' AND LEVEL2 = '12';

SELECT  *FROM trt0101 WHERE INTERFACE_MID in(
SELECT DISTINCT INTERFACE_MID FROM trt0401 WHERE DATASET_ID = '26');

SELECT  *FROM trt0101 WHERE INTERFACE_MID in(
SELECT DISTINCT INTERFACE_MID FROM trt0501 WHERE MAP_ID = '2');

SELECT * FROM TVS0101 ORDER BY COMMIT_DATE DESC;


COMMIT;
SELECT * FROM trt0101;
SELECT * FROM trt0901;

UPDATE TRT0101 
   SET DEPLOY_STATUS  = '1'
       LAST_DEPLOY_DATE = ''
       LAST_DEPLOY_USER = ''
 WHERE INTERFACE_MID ( 
	SELECT INTERFACE_MID FROM trt0501 WHERE MAP_ID = '2')
;
SELECT * FROM tvs0102;

SELECT* FROM tsu0301 WHERE LEVEL1  = 'RT' AND LEVEL2 = '02';

SELECT * FROM trt0102;

SELECT * FROM tvs0101 WHERE data_type = '2' AND COMMIT_DATE >= to_char(SYSDATE ,'yyyymmdd') ORDER BY COMMIT_DATE  DESC ;
commit;

SELECT * FROM TRT0201 WHERE SYSTEM_TYPE = '0';

SELECT sum(CONTENTS_SIZE)/1024 FROM tvs0101 WHERE HEAD = 'Y';

SELECT * FROM tvs0101 ORDER BY DATA_TYPE , DATA_ID , VERSION_NUMBER DESC ;


SELECT * FROM trt0203 WHERE DEFAULT_VALUE  IS NOT NULL AND INPUT_TYPE  = '6';

SELECT * FROM tsu0302 WHERE "PACKAGE" = 'system' AND ATTRIBUTE_ID LIKE 'model%';

SELECT * FROM trt0202 WHERE AID  = '5';

commit;

DELETE FROM TVS0101;
COMMIT;

/* 버전 */
DROP TABLE TVS0101 
	CASCADE CONSTRAINTS;

/* 버전 */
CREATE TABLE TVS0101 (
	DATA_TYPE VARCHAR(5) NOT NULL, /* 데이터유형 */
	DATA_ID VARCHAR(50) NOT NULL, /* 데이터ID */
	VERSION VARCHAR(50) NOT NULL, /* 데이터버전 */
	VERSION_NUMBER INTEGER NOT NULL, /* 버전넘버 */
	HEAD VARCHAR(1) DEFAULT 'N' NOT NULL, /* 해드버전구분 */
	COMMIT_DATE VARCHAR(17) NOT NULL, /* 커밋일시 */
	COMMIT_USER_ID VARCHAR(100) NOT NULL, /* 작성자 */
	CONTENTS BLOB NOT NULL, /* 데이터 */
	CONTENTS_SIZE INTEGER NOT NULL, /* 데이터크기 */
	MSG CLOB NOT NULL, /* 메시지 */
	TAG VARCHAR(255), /* 검색태그 */
	DEL_YN VARCHAR(1) DEFAULT 'N' NOT NULL, /* 삭제여부 */
	MOD_DATE VARCHAR(17), /* 수정일시 */
	MOD_USER_ID VARCHAR(100) /* 수정자 */
);

COMMENT ON TABLE TVS0101 IS '버전';

COMMENT ON COLUMN TVS0101.DATA_TYPE IS '데이터유형';

COMMENT ON COLUMN TVS0101.DATA_ID IS '데이터ID';

COMMENT ON COLUMN TVS0101.VERSION IS '데이터버전';

COMMENT ON COLUMN TVS0101.VERSION_NUMBER IS '버전넘버';

COMMENT ON COLUMN TVS0101.HEAD IS '해드버전구분';

COMMENT ON COLUMN TVS0101.COMMIT_DATE IS '커밋일시';

COMMENT ON COLUMN TVS0101.COMMIT_USER_ID IS '작성자';

COMMENT ON COLUMN TVS0101.CONTENTS IS '데이터';

COMMENT ON COLUMN TVS0101.CONTENTS_SIZE IS '데이터크기';

COMMENT ON COLUMN TVS0101.MSG IS '메시지';

COMMENT ON COLUMN TVS0101.TAG IS '검색태그';

COMMENT ON COLUMN TVS0101.DEL_YN IS '삭제여부';

COMMENT ON COLUMN TVS0101.MOD_DATE IS '수정일시';

COMMENT ON COLUMN TVS0101.MOD_USER_ID IS '수정자';

CREATE UNIQUE INDEX PK_TVS0101
	ON TVS0101 (
		DATA_TYPE ASC,
		DATA_ID ASC,
		VERSION ASC
	);

CREATE INDEX IX_TVS0101
	ON TVS0101 (
		COMMIT_DATE ASC
	);

ALTER TABLE TVS0101
	ADD
		CONSTRAINT PK_TVS0101
		PRIMARY KEY (
			DATA_TYPE,
			DATA_ID,
			VERSION
		);
	
	
	

CREATE UNIQUE INDEX UIX_TVS0101
	ON TVS0101 (
		DATA_TYPE ASC,
		DATA_ID ASC,
		VERSION_NUMBER ASC
	);	
	
	
SELECT * FROM trt0101 WHERE interface_mid = '156';
SELECT * FROM tan0201 WHERE INTERFACE_ID = 'F@00000428';
SELECT * FROM trt0101 WHERE INTERFACE_ID = 'F@00000428';
SELECT * FROM trt0901 ORDER BY DEPLOY_DATE  desc;
		

	SELECT DISTINCT
		    	  e.BUSINESS_CD	   	as "DOMAIN"
		    	 ,b.INTEGRATION_ID	as "MODEL"
		    	 ,g.VAL				as "DESCRIPTION"
		    	 ,im04.NM           as "DATASOURCE"
		    	 ,f.*
		      FROM TRT0101 a
		INNER JOIN TAN0201 b
		 		ON a.INTERFACE_ID 	= b.INTERFACE_ID
		 	   AND a.DEL_YN 	 	= 'N'
		 	   AND b.DEL_YN 		= 'N'	 
		INNER JOIN TAN0101 d
		        ON d.INTERFACE_ID 	= b.INTERFACE_ID
		       AND d.DEL_YN			= 'N'
		INNER JOIN TIM0301 e
		        ON e.BUSINESS_ID 	= d.BUSINESS_ID
		       AND e.BUSINESS_CD 	= 'NCS'
		INNER JOIN TRT0201 f
		        ON f.INTERFACE_MID  = a.INTERFACE_MID
		       AND f.SYSTEM_TYPE 	= '0'
		       --AND f.SYSTEM_ID 		= (SELECT SYSTEM_ID  FROM TIM0101 WHERE SYSTEM_CD = #{systemCd} AND DEL_YN = 'N')
		       AND f.SEQ 			= (SELECT min(SEQ) FROM TRT0201 WHERE INTERFACE_MID = a.INTERFACE_MID AND SYSTEM_TYPE = '0')
		INNER JOIN TRT0202 g
                ON g.INTERFACE_MID 	= a.INTERFACE_MID
               AND g.APP_MID 		= f.APP_MID
        INNER JOIN TRT0203 h
        	    ON h.AID      		= g.AID
        	   AND h.APP_TYPE 		= g.APP_TYPE
        	   AND h.CD       		= 'serviceId'
        	   AND h.DEL_YN   		= 'N'
        INNER JOIN TRT0207 i
                ON i.APP_TYPE 		= f.APP_TYPE
        INNER JOIN TSU0301 im04
        		ON im04.CD 			= i.RSS_CD
               AND im04.LEVEL1 		= 'IM'
		       AND im04.LEVEL2 		= '04' 
		       
		       ;
		      SELECT * FROM TAN0201
		      ;
		     
		   
		     SELECT DISTINCT
		    	 c.BUSINESS_CD	   	as "DOMAIN"
		    	,f.INTEGRATION_ID	as "MODEL"
		    	,h.VAL				as "DESCRIPTION"
		    	,im04.NM            as "DATASOURCE"
		    	,k.*
		      FROM TRT0101 a
		INNER JOIN TAN0101 b
		        ON a.INTERFACE_ID 	= b.INTERFACE_ID
		       AND a.DEL_YN			= 'N'
		       AND b.DEL_YN 		= 'N'
		INNER JOIN TIM0301 c
		        ON c.BUSINESS_ID 	= b.BUSINESS_ID
		       AND c.BUSINESS_CD 	= 'NCS' -- 값 변경 
		INNER JOIN TAN0213 d
				ON d.INTERFACE_ID 	= b.INTERFACE_ID 
			   AND d.NODE_TYPE 		= '0'
			   AND d.SEQ  			= (SELECT min(SEQ) FROM TAN0213 WHERE INTERFACE_ID = d.INTERFACE_ID AND NODE_TYPE = '0')
			   AND d.DEL_YN 		= 'N'
		INNER JOIN TIM0101 e 	  
		  		ON e.SYSTEM_ID  	= d.SYSTEM_ID 
			   AND e.SYSTEM_CD 		= 'CUI' -- 값 변경 
		INNER JOIN TAN0201 f
				ON f.INTERFACE_ID = a.INTERFACE_ID 
		INNER JOIN TRT0201 g
		        ON g.INTERFACE_MID  = a.INTERFACE_MID
		       AND g.SYSTEM_TYPE 	= '2' 
		       AND g.SEQ 			= (SELECT min(SEQ) FROM TRT0201 WHERE INTERFACE_MID = a.INTERFACE_MID AND SYSTEM_TYPE = '2')
		INNER JOIN TRT0202 h
                ON h.INTERFACE_MID 	= a.INTERFACE_MID
               AND h.APP_MID 		= g.APP_MID		
 		INNER JOIN TRT0203 i
        	    ON i.AID      		= h.AID
        	   AND i.APP_TYPE 		= h.APP_TYPE
        	   AND i.CD       		= 'serviceId'
        	   AND i.DEL_YN   		= 'N'   
	    INNER JOIN TRT0207 j
                ON j.APP_TYPE 		= i.APP_TYPE
        INNER JOIN TSU0301 im04
        		ON im04.CD 			= j.RSS_CD
               AND im04.LEVEL1 		= 'IM'
		       AND im04.LEVEL2 		= '04'         	 
		      INNER JOIN TIM0002 k
		   ON k.CHANNEL_ID 	= f.CHANNEL_ID
		 AND k.CHANNEL_CD 	= 'FWS'
		       ;
		       
		      
		      SELECT max(VERSION_NUMBER) + 1
		      FROM TVS0101 
		      WHERE DATA_TYPE = '100' AND DATA_ID = '156' 
		      ;
		      
		     
SELECT * FROM TRT0901 ORDER BY DEPLOY_DATE DESC ;
/* 모델배포 */
DROP TABLE TRT0901 
	CASCADE CONSTRAINTS;

/* 모델배포 */
CREATE TABLE TRT0901 (
	DEPLOY_DATE VARCHAR(14) NOT NULL, /* 배포일시 */
	INTERFACE_MID VARCHAR(50) NOT NULL, /* 인터페이스모델아이디 */
	VERSION VARCHAR(50) NOT NULL, /* 버전 */
	SEQ INTEGER NOT NULL, /* 순번 */
	SYSTEM_ID VARCHAR(50), /* 배포시스템ID */
	SERVER_ID VARCHAR(50), /* 베포서버ID */
	METHOD VARCHAR(5), /* 배포방식 */
	RESULT_CD VARCHAR(5), /* 배모결과코드 */
	RESULT_MSG VARCHAR(4000), /* 배포결과메시지 */
	DEPLOY_USER VARCHAR(100) NOT NULL /* 배포자 */
);

COMMENT ON TABLE TRT0901 IS '모델배포';

COMMENT ON COLUMN TRT0901.DEPLOY_DATE IS '배포일시';

COMMENT ON COLUMN TRT0901.INTERFACE_MID IS '인터페이스모델아이디';

COMMENT ON COLUMN TRT0901.VERSION IS '버전';

COMMENT ON COLUMN TRT0901.SEQ IS '순번';

COMMENT ON COLUMN TRT0901.SYSTEM_ID IS '배포시스템ID';

COMMENT ON COLUMN TRT0901.SERVER_ID IS '베포서버ID';

COMMENT ON COLUMN TRT0901.METHOD IS '배포방식';

COMMENT ON COLUMN TRT0901.RESULT_CD IS '배모결과코드';

COMMENT ON COLUMN TRT0901.RESULT_MSG IS '배포결과메시지';

COMMENT ON COLUMN TRT0901.DEPLOY_USER IS '배포자';

CREATE UNIQUE INDEX PK_TRT0901
	ON TRT0901 (
		DEPLOY_DATE ASC,
		INTERFACE_MID ASC,
		VERSION ASC,
		SEQ ASC
	);

ALTER TABLE TRT0901
	ADD
		CONSTRAINT PK_TRT0901
		PRIMARY KEY (
			DEPLOY_DATE,
			INTERFACE_MID,
			VERSION,
			SEQ
		);

ALTER TABLE TRT0901
	ADD
		CONSTRAINT FK_TRT0101_TO_TRT0901
		FOREIGN KEY (
			INTERFACE_MID
		)
		REFERENCES TRT0101 (
			INTERFACE_MID
		);

	
SELECT * FROM trt0202;
-- 새 CLOB 컬럼을 추가합니다. 
ALTER TABLE TRT0202 ADD (TMP_CONTENTS CLOB); 
-- 데이터를 복사합니다. 
UPDATE TRT0202 SET TMP_CONTENTS = VAL ; 
COMMIT; 
-- 기존 컬럼을 삭제합니다. 
ALTER TABLE TRT0202 DROP COLUMN VAL; 
-- 새로 추가한 임시 컬럼의 이름을 변경합니다. 
ALTER TABLE TRT0202 RENAME COLUMN TMP_CONTENTS TO VAL;

SELECT * FROM trt0203;
-- 새 CLOB 컬럼을 추가합니다. 
ALTER TABLE TRT0203 ADD (TMP_CONTENTS CLOB); 
-- 데이터를 복사합니다. 
UPDATE TRT0203 SET TMP_CONTENTS = DEFAULT_VALUE ; 
COMMIT; 
-- 기존 컬럼을 삭제합니다. 
ALTER TABLE TRT0203 DROP COLUMN DEFAULT_VALUE; 
-- 새로 추가한 임시 컬럼의 이름을 변경합니다. 
ALTER TABLE TRT0203 RENAME COLUMN TMP_CONTENTS TO DEFAULT_VALUE;
 

SELECT* FROM tsu0301 WHERE LEVEL1 = 'RT';

SELECT c.INTERFACE_ID , b.* 
FROM trt0202 a, trt0203 b, trt0101 c , tan0201 
WHERE a.AID = b.AID  AND b.INPUT_TYPE = '6' AND b.DEL_YN = 'N' AND c.INTERFACE_MID = a.INTERFACE_MID AND c.DEL_YN  ='N';
SELECT * FROM tan0201 WHERE INTERFACE_ID = 'F@00000427';


SELECT * FROM tan0101 ORDER BY REG_DATE desc;

SELECT * FROM trt0101 ORDER BY INTERFACE_MID ;
	
SELECT * FROM tsu0301 WHERE LEVEL1 = 'AN';


SELECT * FROM tan0201;
SELECT* FROM tsu0301 WHERE LEVEL1 = 'IM';

  SELECT  *FROM TIM0002;
		SELECT 
		distinct
			 c.BUSINESS_CD	   	as "DOMAIN"
			,f.INTEGRATION_ID	as "MODEL"
			,to_char(h.VAL)				
			,im04.NM            as "DATASOURCE"
		 FROM TRT0101 a
		INNER JOIN TAN0101 b
		   ON a.INTERFACE_ID = b.INTERFACE_ID
		  AND a.DEL_YN = 'N'
		  AND b.DEL_YN = 'N'
		INNER JOIN TIM0301 c
		   ON c.BUSINESS_ID = b.BUSINESS_ID
		INNER JOIN TAN0213 d
		   ON d.INTERFACE_ID = b.INTERFACE_ID
		  AND d.NODE_TYPE = '0'
		  AND d.SEQ = (SELECT min(SEQ) FROM TAN0213 WHERE INTERFACE_ID = d.INTERFACE_ID AND NODE_TYPE = '0')
		  AND d.DEL_YN = 'N'
		INNER JOIN TIM0101 e
		   ON e.SYSTEM_ID = d.SYSTEM_ID
		INNER JOIN TAN0201 f
		   ON f.INTERFACE_ID = a.INTERFACE_ID
		INNER JOIN TRT0201 g
		   ON g.INTERFACE_MID = a.INTERFACE_MID
		  AND g.SYSTEM_TYPE = '2'
		  AND g.SEQ = (SELECT min(SEQ) FROM TRT0201 WHERE INTERFACE_MID = a.INTERFACE_MID AND SYSTEM_TYPE = '2')
		INNER JOIN TRT0202 h
		   ON h.INTERFACE_MID = a.INTERFACE_MID
		  AND h.APP_MID = g.APP_MID
		INNER JOIN TRT0203 i
		   ON i.AID = h.AID
		  AND i.APP_TYPE = h.APP_TYPE
		  AND i.CD = 'serviceId'
		  AND i.DEL_YN = 'N'
		INNER JOIN TRT0207 j
		   ON j.APP_TYPE = i.APP_TYPE
		INNER JOIN TSU0301 im04
		   ON im04.CD = j.RSS_CD
		  AND im04.LEVEL1 = 'IM'
		  AND im04.LEVEL2 = '04'
 ;

SELECT * FROM trt0203;

SELECT * FROM tsu0220;
SELECT * FROM tan0201 WHERE INTERFACE_ID NOT IN (SELECT INTERFACE_ID FROM tsu0220) AND del_yn = 'N' ORDER BY reg_date desc;

SELECT* FROM tsu0218;

SELECT * FROM tsu0301 WHERE LEVEL1 = 'IM';



SELECT * FROM tsu0301 WHERE LEVEL1  = 'RT' AND LEVEL2= '01';
	-- find interfaceId
	SELECT 
		distinct
			 b.INTERFACE_ID 
		 FROM TRT0101 a
		INNER JOIN TAN0101 b
		   ON a.INTERFACE_ID = b.INTERFACE_ID
		  AND a.DEL_YN = 'N'
		  AND b.DEL_YN = 'N'
		INNER JOIN TIM0301 c
		   ON c.BUSINESS_ID = b.BUSINESS_ID
		  AND c.BUSINESS_CD = 'NCM' -- businessCd
		INNER JOIN TRT0201 d
		   ON d.INTERFACE_MID = a.INTERFACE_MID
		  AND d.SYSTEM_TYPE = '2'
		  AND d.SEQ = (SELECT min(SEQ) FROM TRT0201 WHERE INTERFACE_MID = a.INTERFACE_MID AND SYSTEM_TYPE = '2')
		INNER JOIN TRT0202 e
		   ON e.INTERFACE_MID = a.INTERFACE_MID
		  AND e.APP_MID = d.APP_MID
		  AND to_char(e.VAL) = '서비스ID' --serviceId
		INNER JOIN TRT0203 f
		   ON f.AID = e.AID
		  AND f.APP_TYPE = e.APP_TYPE
		  AND f.CD = 'serviceId'
		  AND f.DEL_YN = 'N'
		INNER JOIN TAN0201 g 
		   ON b.INTERFACE_ID  = g.INTERFACE_ID 
		INNER JOIN TIM0002 h 
		   ON g.CHANNEL_ID = h.CHANNEL_ID 
		  AND h.CHANNEL_CD = 'FWS' -- channelCd
		  ;
		  
		 SELECT * FROM tan0201 WHERE INTERFACE_ID  = 'F@00000413';
		 SELECT * FROM tim0002 WHERE CHANNEL_ID = 'CN00000002';
		 
		
		SELECT DISTINCT DATASET_ID FROM TAN0501 WHERE CD = 'SAMPLE-001-UI-001' AND DEL_YN = 'N';
		
	
	
	SELECT * FROM tan0501 WHERE cd = 'NCS12345_O_1';

SELECT * FROM tim0201;

SELECT * FROM tsu0301;

SELECT * FROM tim0101;

SELECT
			a.SYSTEM_ID
			 ,a.SYSTEM_NM
			 ,a.SYSTEM_CD
		FROM TIM0101 a
		WHERE a.DEL_YN = 'N' 
		ORDER BY a.SYSTEM_NM;
	
	
	--NCM(String), OPENAPI-SERVICE-013(String), FWS(String)
				SELECT
					distinct
					b.INTERFACE_ID
				FROM TRT0101 a
				 INNER JOIN TAN0101 b
							ON a.INTERFACE_ID = b.INTERFACE_ID
								AND a.DEL_YN = 'N'
								AND b.DEL_YN = 'N'
				 INNER JOIN TIM0301 c
							ON c.BUSINESS_ID = b.BUSINESS_ID
								AND c.BUSINESS_CD = 'NCM' -- businessCd
				 INNER JOIN TRT0201 d
							ON d.INTERFACE_MID = a.INTERFACE_MID
								AND d.SYSTEM_TYPE = '2'
								AND d.SEQ = (SELECT min(SEQ) FROM TRT0201 WHERE INTERFACE_MID = a.INTERFACE_MID AND SYSTEM_TYPE = '2')
				 INNER JOIN TRT0202 e
							ON e.INTERFACE_MID = a.INTERFACE_MID
								AND e.APP_MID = d.APP_MID
								AND to_char(e.VAL) = 'OPENAPI-SERVICE-014' -- serviceId
				 INNER JOIN TRT0203 f
							ON f.AID = e.AID
								AND f.APP_TYPE = e.APP_TYPE
								AND f.CD = 'serviceId'
								AND f.DEL_YN = 'N'
				 INNER JOIN TAN0201 g
							ON b.INTERFACE_ID  = g.INTERFACE_ID
				 INNER JOIN TIM0002 h
							ON g.CHANNEL_ID = h.CHANNEL_ID
								AND h.CHANNEL_CD = 'FWS' --channelCd
								
SELECT * FROM tan0502;

SELECT * FROM trt0901;
SELECT * FROM tsu0302 WHERE ATTRIBUTE_ID  = 'site.code';


SELECT * FROM tv
								
ALTER TABLE TRT0207 add(CHANNEL_ID varchar(50));
ALTER TABLE TRT0207 add(NODE_TYPE varchar(5));
SELECT * FROM trt0203;
							
UPDATE  tan0201 SET DATA_FREQ  = '9' WHERE interface_id = 'F@00000455';
SELECT * FROM tan0201 WHERE interface_id = 'F@00000455'
UNION 
SELECT * FROM tan0201 WHERE interface_id = 'F@00000437';

DELETE FROM trt0401 WHERE INTERFACE_MID = '183';
COMMIT;
SELECT * FROM tsu0101;
SELECT * FROM tsu0201;
SELECT * FROM trt0202;

SELECT * FROM TRT0102 ORDER BY REG_DATE desc;

SELECT * FROM tsu0302;

SELECT  *FROM tvs0101 WHERE DATA_TYPE  = '4' AND DATA_ID = '156';

SELECT * FROM tan0502 WHERE REF_DATAFIELD_ID  IS NOT null;
------------------------------------------------
--인터페이스모델, 데이터셋 등록 데이터 체크 
------------------------------------------------
SELECT * FROM tan0101 ORDER BY REG_DATE DESC, MOD_DATE  desc;
SELECT * FROM tan0201 ORDER BY REG_DATE DESC, MOD_DATE  desc;
SELECT * FROM tan0213 ORDER BY REG_DATE DESC;
SELECT * FROM tan0218 ORDER BY REG_DATE DESC; --업무매핑 
SELECT * FROM trt0101 ORDER BY REG_DATE DESC, MOD_DATE  desc;

SELECT * FROM trt0201 ORDER BY REG_DATE DESC;

SELECT a.* FROM trt0202 a, trt0201 b WHERE a.INTERFACE_MID = b.INTERFACE_MID AND a.APP_MID = b.APP_MID ORDER BY b.REG_DATE DESC;
SELECT * FROM trt0401 ORDER BY REG_DATE DESC ;

SELECT * FROM tan0501 ORDER BY REG_DATE DESC;
SELECT * FROM tan0502 ORDER BY REG_DATE DESC, TO_NUMBER(DATASET_ID) , TO_NUMBER(DATAFIELD_ID) ;
 
SELECT * FROM TVS0101;


SELECT * FROM tan0327;


	