-- DROP TABLE TSU0901;

CREATE TABLE TSU0901 (
	FETCH_ID VARCHAR(50) NOT NULL, /* 패치ID */
	FETCH_DATE VARCHAR(14) NOT NULL, /* 패치일시 */
	RESULT_CD VARCHAR(255) DEFAULT '0', /* 결과코드 */
	RESULT_MSG VARCHAR(1000), /* 결과메시지 */
	END_DATE VARCHAR(14), /* 패치종료일시 */
	CONTENTS VARCHAR(4000), /* 패치내용 */
	USER_ID VARCHAR(50) /* 패치유저ID */
);

COMMENT ON TABLE  TSU0901 IS '설치(패치)결과';

COMMENT ON COLUMN  TSU0901.FETCH_ID IS '패치ID';

COMMENT ON COLUMN  TSU0901.FETCH_DATE IS '패치일시';

COMMENT ON COLUMN  TSU0901.RESULT_CD IS '결과코드';

COMMENT ON COLUMN  TSU0901.RESULT_MSG IS '결과메시지';

COMMENT ON COLUMN  TSU0901.END_DATE IS '패치종료일시';

COMMENT ON COLUMN  TSU0901.CONTENTS IS '패치내용';

COMMENT ON COLUMN  TSU0901.USER_ID IS '패치유저ID';

CREATE UNIQUE INDEX PK_TSU0901
	ON  TSU0901 (
		FETCH_ID ASC,
		FETCH_DATE ASC
	);	

/* 인터페이스레코드처리현황(일) */
--DROP TABLE TSU0811 CASCADE CONSTRAINTS;

/* 인터페이스레코드처리현황(월) */
--DROP TABLE IF EXISTS TSU0812  CASCADE CONSTRAINTS;

/* 인터페이스레코드처리현황 */
--DROP TABLE IF EXISTS TSU0810  CASCADE CONSTRAINTS;

/* 인터페이스레코드처리현황(일) */
CREATE TABLE TSU0811 (
	INTERFACE_ID VARCHAR(50) NOT NULL, /* 인터페이스ID */
	TR_DAY VARCHAR(8) NOT NULL, /* 처리일 */
	SUCCESS_R_CNT INTEGER, /* 성공레코드건수 */
	ERROR_R_CNT INTEGER, /* 에러레코드건수 */
	PROCESS_R_CNT INTEGER, /* 미완료레코드건수(진행중) */
	REG_DATE VARCHAR(17) NOT NULL, /* 등록일 */
	REG_APP VARCHAR(100) NOT NULL /* 등록APP */
);

COMMENT ON TABLE TSU0811 IS '인터페이스레코드처리현황(일)';

COMMENT ON COLUMN TSU0811.INTERFACE_ID IS '인터페이스ID';

COMMENT ON COLUMN TSU0811.TR_DAY IS '처리일';

COMMENT ON COLUMN TSU0811.SUCCESS_R_CNT IS '성공레코드건수';

COMMENT ON COLUMN TSU0811.ERROR_R_CNT IS '에러레코드건수';

COMMENT ON COLUMN TSU0811.PROCESS_R_CNT IS '미완료레코드건수(진행중)';

COMMENT ON COLUMN TSU0811.REG_DATE IS '등록일';

COMMENT ON COLUMN TSU0811.REG_APP IS '등록APP';

CREATE UNIQUE INDEX PK_TSU0811
	ON TSU0811 (
		INTERFACE_ID ASC,
		TR_DAY ASC
	);

/* 인터페이스레코드처리현황(월) */
CREATE TABLE TSU0812 (
	INTERFACE_ID VARCHAR(50) NOT NULL, /* 인터페이스ID */
	TR_MONTH VARCHAR(6) NOT NULL, /* 처리월 */
	SUCCESS_R_CNT INTEGER, /* 성공레코드건수 */
	ERROR_R_CNT INTEGER, /* 에러레코드건수 */
	PROCESS_R_CNT INTEGER, /* 미완료레코드건수(진행중) */
	REG_DATE VARCHAR(17) NOT NULL, /* 등록일 */
	REG_APP VARCHAR(100) NOT NULL /* 등록APP */
);

COMMENT ON TABLE TSU0812 IS '인터페이스레코드처리현황(월)';

COMMENT ON COLUMN TSU0812.INTERFACE_ID IS '인터페이스ID';

COMMENT ON COLUMN TSU0812.TR_MONTH IS '처리월';

COMMENT ON COLUMN TSU0812.SUCCESS_R_CNT IS '성공레코드건수';

COMMENT ON COLUMN TSU0812.ERROR_R_CNT IS '에러레코드건수';

COMMENT ON COLUMN TSU0812.PROCESS_R_CNT IS '미완료레코드건수(진행중)';

COMMENT ON COLUMN TSU0812.REG_DATE IS '등록일';

COMMENT ON COLUMN TSU0812.REG_APP IS '등록APP';

CREATE UNIQUE INDEX PK_TSU0812
	ON TSU0812 (
		INTERFACE_ID ASC,
		TR_MONTH ASC
	);

/* 인터페이스레코드처리현황 */
CREATE TABLE TSU0810 (
	INTERFACE_ID VARCHAR(50) NOT NULL, /* 인터페이스ID */
	TR_DATE VARCHAR(14) NOT NULL, /* 처리시간 */
	SEQ INTEGER NOT NULL, /* 순번 */
	SUCCESS_R_CNT INTEGER, /* 성공레코드건수 */
	ERROR_R_CNT INTEGER, /* 에러레코드건수 */
	PROCESS_R_CNT INTEGER, /* 미완료레코드건수(진행중) */
	REG_DATE VARCHAR(17) NOT NULL, /* 등록일 */
	REG_APP VARCHAR(100) NOT NULL /* 등록APP */
);

COMMENT ON TABLE TSU0810 IS '인터페이스레코드처리현황';

COMMENT ON COLUMN TSU0810.INTERFACE_ID IS '인터페이스ID';

COMMENT ON COLUMN TSU0810.TR_DATE IS '처리시간';

COMMENT ON COLUMN TSU0810.SEQ IS '순번';

COMMENT ON COLUMN TSU0810.SUCCESS_R_CNT IS '성공레코드건수';

COMMENT ON COLUMN TSU0810.ERROR_R_CNT IS '에러레코드건수';

COMMENT ON COLUMN TSU0810.PROCESS_R_CNT IS '미완료레코드건수(진행중)';

COMMENT ON COLUMN TSU0810.REG_DATE IS '등록일';

COMMENT ON COLUMN TSU0810.REG_APP IS '등록APP';

CREATE UNIQUE INDEX PK_TSU0810
	ON TSU0810 (
		INTERFACE_ID ASC,
		TR_DATE ASC,
		SEQ ASC
	);




